---
- name: Stat nix binary in local user dir
  stat:
    path: "{{ ansible_user_dir }}/.nix-profile/etc/profile.d/nix.sh"
  register: nix_bin
  
- name: install Nix
  block:
    - name: create /nix directory owned by current user
      file:
        state: directory
        path: /nix
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: u=rwx,g=rx,o=rx
      become: yes

    - name: set kernel parameters for Nix installation
      copy:
        content: kernel.unprivileged_userns_clone=1  
        dest: /etc/sysctl.d/nix.conf
      become: yes

    - name: reload kernel paramters preferences
      command: /sbin/sysctl --system
      become: yes

    - name: create temporary directory for Nix installator
      command: mktemp --suffix -nix-installator
      register: tmpfile

    - name: download Nix installation script
      get_url:
        url: https://nixos.org/nix/install 
        checksum: sha512:f6bd178c35d13cd8ad664450d6bfdaa054cd0abe1a094912ac6a1eced6d41f5ff7052041b25406df4b301e802c131970905ebe790566a7f89efcf231b14b80bf
        dest: "{{ tmpfile.stdout }}"
        mode: u+x

    - name: execute Nix installation script
      shell: NIX_INSTALLER_NO_MODIFY_PROFILE='1' {{ tmpfile.stdout | quote }} --no-daemon
  when: not nix_bin.stat.exists

- name: install nix packages
  shell: . {{ ansible_user_dir }}/.nix-profile/etc/profile.d/nix.sh && nix-env -if {{ ansible_user_dir }}/Dotfiles/nix/manifest.nix
  changed_when: no
  tags:
    - pkg

- set_fact:
    nix_helpers_repos:
      - fetch: https://github.com/allgreed/nix-manifest-format.git
        push: git@github.com:allgreed/nix-manifest-format.git
        location: ~/Desktop/nix-manifest-format
      - fetch: https://github.com/allgreed/inotifywait-symlink-target.git
        push: git@github.com:allgreed/inotifywait-symlink-target.git
        location: ~/Desktop/inotifywait-symlink-target

- name: clone depndant repositories
  git:
    repo: "{{ item.fetch }}"
    dest: "{{ item.location }}"
  ignore_errors: yes # added for local ansible files developement - local changes are present in the repository
  loop: "{{ nix_helpers_repos }}"

- name: set remote-push over SSH for depndant repositories
  git_config:
    name: remote.origin.pushurl
    scope: local
    value: "{{ item.push }}"
    repo: "{{ item.location }}"
  loop: "{{ nix_helpers_repos }}"

- name: install nix-manifest-tracker service
  template:
    src: nix-manifest-tracker.service.j2
    dest: /etc/systemd/system/nix-manifest-tracker.service
  become: yes
  register: nix_manifest_tracker_installation

- name: propagate service changes
  systemd: daemon_reload=yes
  become: yes
  changed_when: yes
  notify:
    - reload nix-manifest-tracker
  when: nix_manifest_tracker_installation.changed

- name: start and enable nix-manifest-tracker
  service:
    name: nix-manifest-tracker
    enabled: true
    state: started
  become: yes
